name: Release Go Binaries

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
      - uses: actions/checkout@v4

      - name: Set APP_VERSION env
        run: echo "APP_VERSION=${GITHUB_REF_NAME}" >> "${GITHUB_ENV}"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_path: .
          binary_name: aru
          asset_name: aru_${{ matrix.goos }}_${{ matrix.goarch }}
          extra_files: LICENSE README.md
          md5sum: false
          overwrite: true
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          pre_command: export CGO_ENABLED=0
          ldflags: -s -w -X "main.Version=${{ env.APP_VERSION }}"
